services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    buildCommand: docker build -t laravel-app . && docker run -d -p 80:80 laravel-app
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:your_app_key_here
      - key: APP_DEBUG
        value: false
