version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    container_name: nginx-container
    volumes:
      - ./:/var/www/
      - ./_Docker/Nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - application

  psql:
    image: postgres:14.18
    restart: always
    ports:
      - "8081:5432"
    container_name: database-container
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./tmp/db:/var/lib/postgresql

  application:
    build:
      context: .
      dockerfile: _Docker/Application/Dockerfile
    container_name: application-container
    volumes:
      - ./:/var/www/